/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stegnography_application;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Azmi
 */
public class Decoding_Stegano_Application extends javax.swing.JFrame {

    
    //My Private Variables Declaration
    private static String steganoImagePath;
    private static String path;
    private static boolean selectSteganoImageButtonIsPressed = false;
    //End Private Variables Declaration
    
    /**
     * Creates new form Decoding_Stegano_Application
     */
    public Decoding_Stegano_Application() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShowSteganoImageLabel = new javax.swing.JLabel();
        SelectSteganoImageButton = new javax.swing.JButton();
        FinishButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SelectSteganoImageButton.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        SelectSteganoImageButton.setText("Select Image");
        SelectSteganoImageButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.darkGray, java.awt.Color.black, java.awt.Color.darkGray));
        SelectSteganoImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectSteganoImageButtonActionPerformed(evt);
            }
        });

        FinishButton.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        FinishButton.setText("Finish");
        FinishButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.darkGray, java.awt.Color.black, java.awt.Color.darkGray));
        FinishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ShowSteganoImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SelectSteganoImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(FinishButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowSteganoImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SelectSteganoImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                        .addComponent(FinishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectSteganoImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectSteganoImageButtonActionPerformed
        // TODO add your handling code here:
        File file;
        String imagePath;
        boolean pngbool, bmpbool;
        do{
            ShowSteganoImageLabel.setIcon(null);
            File_Chooser fileChooser = new File_Chooser();
            file = fileChooser.file_Chooser(ShowSteganoImageLabel);

            imagePath = file.getAbsolutePath();
            
            pngbool = imagePath.endsWith(".png");
            bmpbool = imagePath.endsWith(".bmp");
            if(pngbool){
                bmpbool = pngbool;
            }
            else if(bmpbool){
                pngbool = bmpbool;
            }
        }
        while(pngbool != true || bmpbool != true);    

        set_SteganoImagePath(imagePath);
        setPath(file.getParent());

    }//GEN-LAST:event_SelectSteganoImageButtonActionPerformed

    private void FinishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishButtonActionPerformed
        // TODO add your handling code here:
        if(selectSteganoImageButtonIsPressed == true){
            Calling_decode();
            int again = JOptionPane.showConfirmDialog(null, "Do you want to do again?", "AGAIN",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if(again == 0){//0 = yes
                selectSteganoImageButtonIsPressed = false;
                ShowSteganoImageLabel.setIcon(null);
                Stegano_Application stegano_Application = new Stegano_Application();
                dispose();
                stegano_Application.setVisible(true);
            }
            else{
                dispose();
                System.exit(0);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Select Any Image","IMAGE NOT SELECTED",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_FinishButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Decoding_Stegano_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Decoding_Stegano_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Decoding_Stegano_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Decoding_Stegano_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Decoding_Stegano_Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FinishButton;
    private javax.swing.JButton SelectSteganoImageButton;
    private javax.swing.JLabel ShowSteganoImageLabel;
    // End of variables declaration//GEN-END:variables

    
    /**
     * Create setPath() method to set the path of the cover image
     */
    private void set_SteganoImagePath(String text) {
        steganoImagePath = text;
        selectSteganoImageButtonIsPressed = true;
    }
    
    /**
     * Create getPath() method to get the path of the cover image
     * @return 
     */
    public String get_CoverImagePath(){
       return steganoImagePath;
    }

    /**
     * Create setPath() method to set the path without any fileName
     */
    private void setPath(String text) {
        path = text;
    }
    
    /**
     * Create getPath() method to get the path
     * @return 
     */
    public String getPath(){
       return path;
    }

    private boolean Calling_decode() {
        
        Decoding_Steganography_Application decoding_Steganography_Application = new Decoding_Steganography_Application();
        String decode = decoding_Steganography_Application.decode(path, steganoImagePath);
        
        if(decode.equals("done")){
            System.out.println("File Is Formed");
            JOptionPane.showMessageDialog(null, "File Is Formed");
        }
        else{
            System.out.println(decode);
            JOptionPane.showMessageDialog(null, "Your message :  "+ decode);
        }
        return true;
    }
    
}
